### ISSUE TITLE
which hardware devices are supported?

### ISSUE THREAD

**Issue by tomholub** [Nitrokey/nitrokey-webcrypt#25]
from this list: https://www.nitrokey.com/ which of the devices are targeted for webcrypt OpenPGP support? In particular I'd like to know which devices can I test this PR https://github.com/openpgpjs/openpgpjs/pull/1567 with

**Comment by szszszsz** [comment]
Hi!
1. Nitrokey 3 is the only device planned to receive support for Nitrokey Webcrypt as of now. Stable firmware does not cover it yet, but we offer alpha firmware for tests (these so far were published [here](https://github.com/Nitrokey/nitrokey-webcrypt-rust/releases)).
2. For the development and quick tests an USB-IP simulation is as good;it can be run on any modern Linux machine, and routed over USB-IP to other platforms.
The one I am using currently for quick tests is:
    - https://github.com/Nitrokey/nitrokey-webcrypt-usbip/    
    (let me know in case there would be any trouble with its setup)

In the future the following project will take this responsibility, which is configured after the Nitrokey 3 firmware:
- https://github.com/Nitrokey/nitrokey-3-firmware/tree/main/runners/usbip

**Comment by tomholub** [comment]
I now see on https://github.com/Nitrokey/nitrokey-webcrypt-rust/releases that it says "Nitrokey 3 CN / LPC55" - can I get my hands on this particular device? I'd prefer to test on actual hardware, if possible. Or I should theoretically be able to use that firmware on any of these? https://shop.nitrokey.com/shop?&search=Nitrokey%203 (though I supposed it was not tested with all of them yet?)

**Comment by szszszsz** [comment]
Good question.
All Nitrokey 3 variants share the source code, and the supported applications. I do not know about the alpha schedule though - will ask internally and get back to you.
Alternatively, you can order a "hacker" device, which does not have the bootloader locked - that would allow flashing your own firmware.

**Comment by szszszsz** [comment]
Hey! Sorry for the delay! It's been 3 weeks already, and half of the time I was feeling sick.

Back to the question, any Nitrokey 3 will be good for the tests. If you plan to test Nitrokey Webcrypt over NFC, you might want to get Nitrokey 3 A/C.

**Comment by tomholub** [comment]
Thanks :+1:
