### ISSUE TITLE
Command: Generate non-resident ECC key

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-webcrypt#5]

**Comment by szszszsz** [comment]
Closing this issue and similar ones as done.

Implementation is provided in Nitrokey FIDO2 firmware repository, branch `nitrokey-webcrypt`. Tests are located in `./tests/webcrypt-tests/`. Documentation provided in current repository for the reference at `implementation.md`. Direct links:
- https://github.com/Nitrokey/nitrokey-fido2-firmware/tree/nitrokey-webcrypt
- https://github.com/Nitrokey/nitrokey-fido2-firmware/tree/nitrokey-webcrypt/tests/webcrypt-tests
- https://github.com/Nitrokey/nitrokey-webcrypt/blob/master/implementation.md
